# fly.toml app configuration file generated for podcast-server on 2023-10-24T17:55:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "podcast-server"
primary_region = "waw"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
